name: Rebuild Distribution Index and HTML

on:
  repository_dispatch:
    types: [addon_published]
  #push:
  #  branches:
  #    - main
  #  paths:
  #    - 'metadata/**.json'
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  rebuild:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Distribution Repository
        uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.13'

      - name: Install jinja2
        run: pip install jinja2

      - name: Rebuild index
        env:
          ADDON_META_JSON: ${{ github.event.client_payload.addon_meta }}
        run: python .github/scripts/generate_index.py

      - name: Commit and Push Distribution Artifacts
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add index.json index.html
          if ! git diff --cached --exit-code; then
            git commit -m "chore: Auto-rebuild distribution index"
            git push origin main
          else
            echo "変更はありませんでした。"
          fi
